### ISSUE TITLE
Can't download the signature file

### ISSUE THREAD

**Issue by MokshitSurana** [builtbybel/Bloatynosy#101]
Getting error: Unable to connect to the remote server

![image](https://github.com/builtbybel/BloatyNosy/assets/72140092/2b1ea70b-1af1-4dc5-a91e-cd024d47f4b4)
![image](https://github.com/builtbybel/BloatyNosy/assets/72140092/44d44678-01e7-4550-94d1-e7330873a44a)

**Comment by Belim** [comment]
WinModder is obsolete . please use latest 1.x release
