### ISSUE TITLE
File explorer changed to old style 

### ISSUE THREAD

**Issue by tharanijpt** [builtbybel/BloatyNosy#102]
hey i try to debloat and turn off some telemetry and my file explorer changed to the old style, is there a way to revert it

![Screenshot 2023-11-23 150420](https://github.com/builtbybel/BloatyNosy/assets/133520025/517fef43-33d7-40b9-ae80-eb4102a9f8e0)

**Comment by lilrajoo** [comment]
hiya do you know how to revert this i have this issue too:>

**Comment by tharanijpt** [comment]
hey dude have you solved the issue

**Comment by tharanijpt** [comment]
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell
Extensions
go to this location in your registry editor and see is there any folder
named "blocked"  under shell extensions and inside the folder if you see
this key "{e2bf9676-5f8f-435c-97eb-11607a5bedf7}" it is responsible for the
change you can delete it and restart to change to windows 11 style

the location may not be same for you and me if that case go manually in
registry

hope this helps

**Comment by lilrajoo** [comment]
hey i dont have any blocked folders under shell extensions, there are only approved and cahed folders there

**Comment by tharanijpt** [comment]
hey the mistake we made here is directly run the tool if you see the
explorer option in the tool there is an option called enable window 10 file
explorer that is the reason for the confusion.

Step 1: The way I suggest is to once again open the tool and run the
restore defaults and restart the windows mostly this resolves the issue, in
my case i ran thisiswin11 tool im not sure that whether you run BloatyNosy
or Thisiswin11.
Step2: After this many processes starts to run and windows will be bloaty
again so I recommend once again run the script and ensure that you* untick
the option *this time*.  *
[image: image.png]
hope this fix your issue

https://github.com/builtbybel/ThisIsWin11/blob/main/src/TIW11/Modules/OpenTweaks/Assessments/Explorer/FileExplorer.cs
I think this is the script that is resposible for the changes

**Comment by lilrajoo** [comment]
hi i ran bloatynosy, ill try this and search for such a option thx will update u

**Comment by lilrajoo** [comment]
hey i fixed it thx for ur help:>

**Comment by tharanijpt** [comment]
Glad it worked!
