### ISSUE TITLE
latest version: in admin mode,  The term 'Requires' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by fasteddys** [builtbybel/Bloatynosy#113]
` The term 'Requires' is not recognized as the name of a cmdlet, function, script file, or operable program`

<img width="699" alt="image" src="https://github.com/builtbybel/Bloatynosy/assets/96149622/364c6779-7a5a-43e4-9f7b-0ba2dedab9c0">

**Comment by Belim** [comment]
some lines ps scipts. fixed!
