### ISSUE TITLE
Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by pythagorasg** [builtbybel/BloatyNosy#12]
Trojan:Script/Wacatac.B!ml

**Comment by pmarkoulidakis** [comment]
Check #3

**Comment by Belim** [comment]
false positive and under analysis https://www.microsoft.com/en-us/wdsi/submission/3f7ebd8d-eff7-44b7-84f2-e38f6d4bc91c

**Comment by pythagorasg** [comment]
thnx
