### ISSUE TITLE
BloatyNosy 0.32 - Asks for some unnamed app and fails to search for it on the Windows Store

### ISSUE THREAD

**Issue by sh-ravan** [builtbybel/Bloatynosy#13]
When I try to run the app, it asks for some unnamed app and fails to search for it on the Windows Store. What am I missing?

![image](https://user-images.githubusercontent.com/83463078/220997081-584a0f5e-825b-4701-90af-f8b33b3f184e.png)

Edit: just downloaded [BloatyNosy 0.31](https://github.com/builtbybel/BloatyNosy/releases/tag/0.31.0) and it runs fine 🤷

**Comment by Belim** [comment]
Hallelujah 🙏

**Comment by Belim** [comment]
Hold on a moment. You're using the wrong version: 
0.32 https://github.com/builtbybel/BloatyNosy/releases/tag/0.32.0 has just been released 😆
