### ISSUE TITLE
Errors and confusing UI, Apply fix button

### ISSUE THREAD

**Issue by ridingmower** [builtbybel/BloatyNosy#15]
Hello, this is nice but it assumes familiarity with the UI.

- [ ] IMHO recommend a step/UI setting, and when the user selects the settings he wants, `show a button apply the fixes`, the drop down is not obvious or front and center
![image](https://user-images.githubusercontent.com/114959579/221376827-02df1aa4-d71d-486e-bc4d-ab2407b59d76.png)
And have button to Say `APPLY FIX` or `Fix Now`  
![image](https://user-images.githubusercontent.com/114959579/221376962-015dde1b-bbd8-4857-8e31-22f1b6c7d0bd.png)

_______________
It crashes:
- [ ] include some info on how to get past or restart in admin (which I ran but still same results) ![image](https://user-images.githubusercontent.com/114959579/221376671-d6a01264-23cc-40f6-993d-5efef0d98358.png)
- [x] HP bloatware seems very stubborn , and hidden with changing names.
- [x] Windows does not allow us to download, marks as dangerous/discard

**Comment by Belim** [comment]
@ridingmower - You're right, but I hate buttons 😩

**Comment by Belim** [comment]
imho, x64-bit binary does not throw a false positive https://www.virustotal.com/gui/file/c780694cd840799692016acfea881cf4885fa1036bc26883b037ee313d6cbd8a?nocache=1
