### ISSUE TITLE
Deleted Series Tracker app

### ISSUE THREAD

**Issue by whatdoihavetodo** [builtbybel/BloatyNosy#17]
I was cleaning up an existing installation.  So far, noticed that the Series Tracker app is gone.  Years of work accumulating a list of shows, gone.

Had no idea BloatyNosy would delete an app I added myself.  It is a Microsoft store free app.

If I can figure where the data was stored, might be able to pull from an old backup.  Sheesh.

**Comment by Belim** [comment]
**This app is not removed by BloatyNosy by default.**
 If you use the BloatFinder and move all apps to the trash without thinking, you do so at your own risk. Unfortunately, everything in life has consequences.
