### ISSUE TITLE
Decrapify does not remove selected app packages

### ISSUE THREAD

**Issue by CodingMadness** [builtbybel/Bloatynosy#189]
Title. 

When I use decrapify, and I select unwanted app-packages and i hit "Remove selected (manual)" then the AI pilot outputs **seemingly** a log which said files are removed but when i run in powershell : " Get-AppxPackage -AllUsers" it shows that they are still there (see image attached below) and also there is only 1 user account on this PC.

![grafik](https://github.com/builtbybel/Winpilot/assets/28008874/2f66ed40-a659-4b21-ab07-88cc2fe18025)

I removed "AAD Brokerplugin" and others via your app and it still shows.. they are installed

**Comment by Belim** [comment]
the package can't be deleted either, and Clippy reports that accordingly. All good!

**Comment by CodingMadness** [comment]
> the package can't be deleted either, and Clippy reports that accordingly. All good! In the current version 3.5, you should have received the following message: "Failed to remove package: Microsoft.AAD.BrokerPlugin"

I have read that other debloating tools report that Microsoft made it way harder to remove those, is there really no chance of getting rid of them **entirely**?

**Comment by CodingMadness** [comment]
> the package can't be deleted either, and Clippy reports that accordingly. All good! In the current version 3.5, you should have received the following message: "Failed to remove package: Microsoft.AAD.BrokerPlugin"

yea it gives me an error message but it disappears to quickly, would be nice to see a detailed log being printed out somewhere so i can have a closer view on it :/

**Comment by Belim** [comment]
I ain't letting those apps declared as system by Microsoft get removed either. Its doable sure, but Im all about lending a hand with the app, not stirring up more trouble 😸  Maybe in future versions, i could hide some of those system apps though. Clippy's output message stays open until you click elsewhere with the mouse. Not sure how else to handle it. Maybe keeping a history could work, though.
