### ISSUE TITLE
Can't get into sign in options & fingerprint login not working after bloatware cleanup

### ISSUE THREAD

**Issue by evillurker** [builtbybel/Bloatynosy#192]
As the title says after I cleaned up bloatware my windows 11 can't get me into the sign in options screen and the fingerprint doesnt work anymore, how can I restore previous settings?

**Comment by MacDos** [comment]
I have had the same problem with the fingerprint hardware, I had a RE-restore-point in Windows11 to get away from Winpilot. 
In my case, the Windows-Defender blocked 3 files also.
