### ISSUE TITLE
Plan on Releasing on winget or scoop?

### ISSUE THREAD

**Issue by nahid6970** [builtbybel/Bloatynosy#200]
is there any plan on releasing the app on winget or scoop package manager?

**Comment by Belim** [comment]
I haven't tackled that yet. Ready to drop a manifest in the winget repo? I'm all in 😸

**Comment by beedell-roke** [comment]
@Belim, if one submits this at [`microsoft/winget-pkgs/issues/new?template=package_request.yml`](https://github.com/microsoft/winget-pkgs/issues/new?assignees=&labels=Help-Wanted%2CPackage-Request&projects=&template=package_request.yml&title=%5BPackage+Request%5D%3A+), they don't need to create a manifest.

**Comment by aliesbelik** [comment]
ScoopInstaller/Extras#17897
