### ISSUE TITLE
Application Dump, narrow columns

### ISSUE THREAD

**Issue by toomm1** [builtbybel/Bloatynosy#244]
new Version 0.87.1, Application Dump, the left column with the display of the applications has become very narrow compared to the last version, you can no longer recognize exactly which application it is at first glance...

The right-hand column with the information has also become narrower.

![Screenshot 2024-11-29 104401](https://github.com/user-attachments/assets/26424f66-9459-44f7-84e6-88cbb717cbdc)

**Comment by Belim** [comment]
Maximizing the window should help, especially on high DPI resolutions 🤔
