### ISSUE TITLE
How to use your App

### ISSUE THREAD

**Issue by ghettobuilder2027** [builtbybel/Bloatynosy#245]
Hi
I am trying to use your app but do not find an exe file to launch it. I installed powershell to try to launch the different scripts but without success. Could you point me to a tutorial to launch the scripts or to get to the launch the app properly.  
Many thanks in advance

**Comment by Belim** [comment]
Oh, you just need to download the following .exe from the assets, please
https://github.com/builtbybel/Bloatynosy/releases/download/0.87.1/Bloatynosy.Nue.exe
