### ISSUE TITLE
Issue with the "Bloat Finder"

### ISSUE THREAD

**Issue by RandomUserOfGitHub01** [builtbybel/Bloatynosy#25]
After installing the BloatNosy 22621.1413 build and using the BloatFinder application, my Windows 11 OS has been having all sorts of issues including:

- Windows Settings keeps prematurely closing unexpectedly
- cannot open some webpage extensions that I could previously 
- background display is no longer mapped to the monitors correctly

When selecting the BloatFinder application to revert the settings back to default I get the following error message:

"Unhandled exception has occurred in your application. If you click Continue, the application will ignore and attempt to continue.  If you click Quit, the application will close immediately.

Object reference not set to an instance of object."

When opening the Details button the following information is provided:

" 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BloatyNosy.AppsPageView.InitializeAppsSystem()
   at BloatyNosy.AppsPageView..ctor()
   at BloatyNosy.MainForm.cmbTools_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
BloatyNosy
    Assembly Version: 0.41.0.0
    Win32 Version: 0.41.0
    CodeBase: file:///C:/Users/j_kol/AppData/Local/Temp/Temp2_BloatyNosyApp.zip/BloatyNosy.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management.Automation
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.22621.963
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box. "

```

I am have so far been unable to get this resolved.

**Comment by Belim** [comment]
> After installing the BloatNosy 22621.1413 build and using the BloatFinder application, my Windows 11 OS has been having all sorts of issues including:
> 
> * Windows Settings keeps prematurely closing unexpectedly
> * cannot open some webpage extensions that I could previously
> * background display is no longer mapped to the monitors correctly

Which apps did you uninstall? I am not aware of any app, even system apps, that can cause such crashes unless you managed to uninstall the Microsoft.UI.XAML package. However, this is not possible with the Bloatfinder.

> 
> When selecting the BloatFinder application to revert the settings back to default I get the following error message:
> 

The BloatFinder doesn't offer an undo function at all. Can you please explain in detail how to initiate the exception ?

**Comment by RandomUserOfGitHub01** [comment]
> Which apps did you uninstall? I am not aware of any app, even system apps, that can cause such crashes unless you managed to uninstall the Microsoft.UI.XAML package. However, this is not possible with the Bloatfinder.

The only app I uninstalled before downloading and installing BloatNosy from the GitHub was ASUS Armoury Crate. 

I also disabled the remanent System Services of the ASUS bloatware.

> The BloatFinder doesn't offer an undo function at all. Can you please explain in detail how to initiate the exception?

Where it states "Fix" in the dropdown, there is/was another option to "Restore to default".

![BloatNosy - BloatFinder - Reset yo Default Issue](https://user-images.githubusercontent.com/129490723/230749935-2eeb5090-1b32-4aaa-8fcd-52768ea879dd.gif)

I ended up having to reinstall Windows 11 and all other software on my laptop. 

The BloatNosy software was downloaded via GitHub and not the Microsoft Store.

**Comment by freddyli** [comment]
Same issue for me - unfortunately can't try this app - will try ThisIsWin11 next

**Comment by Belim** [comment]
The exception is triggered when you want to switch directly to the BkoatFinder module.
Did you extract the app from a zip archive?

**Comment by LarsErikOsterud** [comment]
Get this exception no matter what I try to do. Can't disable or uninstall anything. Exception for everything.
Is there any service or component that is necessary?  (tried windows 10 debloater and that works fine)
