### ISSUE TITLE
Whatsapp desktop

### ISSUE THREAD

**Issue by fraizzo** [builtbybel/BloatyNosy#36]
After debloated whatsapp desktop app is uninstalled and impossible to reinstall from microsoft store, the error:

![image](https://user-images.githubusercontent.com/43107728/234493536-49a8dffa-1275-4810-966b-d9d2a35109e0.png)

**Comment by Belim** [comment]
It's not related to debloating. The problem lies with the store.

**Comment by fraizzo** [comment]
> It's not related to debloating. The problem lies with the store.

yes, you know how can i resolve?
