### ISSUE TITLE
Adding ExplorerPatcher in InstaPackage and Issue with WinModder

### ISSUE THREAD

**Issue by Vipin2003** [builtbybel/Bloatynosy#41]
1. Bro, pls add Explorer patcher also in InstaPackage like you have added StartAllBack. Also add selection between them like If user select Explorer Patcher, then, SAB will be greyed out and vice-versa. As installing them together conflicts system settings.

2. There is a issue with WinModder that if we select the mods that we want to apply and select apply, then, it will only run that mod which is selected (i mean highlighted). It doesn't apply all the selected. We have to apply the mods 1-by-1 by selecting them. Please check this.

**Comment by Belim** [comment]
Only winget repositories are supported. Does the EP tool have a repo there?

**Comment by Vipin2003** [comment]
winget reo...idk about that. but i found it on winstall

https://winstall.app/apps/valinet.ExplorerPatcher

Is it enough??

**Comment by Belim** [comment]
Its online https://github.com/builtbybel/BloatyNosy/blob/main/assets/packages.git 😺

**Comment by Vipin2003** [comment]
And bro, what about the 2nd issue...have you found any solution for it

**Comment by Belim** [comment]
yes, switch to the current 1.x release. the winmodder may be history here, but the plugins allow multiselect
