### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by LyndonGingerich** [builtbybel/BloatyNosy#51]
I'm loving BloatyNosy. I'm finding it very slow to load when I start it, though. InstaPackage is also taking a long time to load when I select it.

I have a persistent Internet connection. I am using a proxy, but I observed freezing in BloatyNosy before the proxy was added.

Also, would it be possible to keep the app responsive while checking for updates?

Version in use: 0.70.101

**Comment by Belim** [comment]
Can you measure the loading times until the main form is displayed? Were the old versions faster than the current 0.70x? I can't detect any difference between the old and new version.

**Comment by Belim** [comment]
Does anyone else have trouble starting up or experiencing slow loading times for the main application?

**Comment by LyndonGingerich** [comment]
Out of curiosity, are you then just going to have people restart their computers after installing BloatyNosy?
