### ISSUE TITLE
Could not find a part of the path 'C:\Program Files\Builtbybel\BloatyNosy\app\bloaty.txt' 

### ISSUE THREAD

**Issue by krypdoh** [builtbybel/BloatyNosy#54]
Get an error during fix
Microsoft.NET Framework
Could not find a part of the path 'C:\Program Files\Builtbybel\BloatyNosy\app\bloaty.txt'

I was able to suppress this error by creating a blank text file **bloaty.txt** and the **app** folder in C:\Program Files\Builtbybel\BloatyNosy\

![bn-bloatytxt](https://github.com/builtbybel/BloatyNosy/assets/105649039/6d2cd3b9-1ad1-45ce-a8cc-710e600c1be5)

**Comment by Belim** [comment]
Thanks, I believe I have also addressed that in the upcoming release that will be published shortly.

**Comment by p1xeltw0** [comment]
> ![изображение](https://user-images.githubusercontent.com/87097942/258403248-3ea44edc-6a67-4c37-94cb-be9eb5be75ee.png) Ошибка по-прежнему выскакивала, пока я устанавливал новую Windows 11.


Have you solved the problem?

**Comment by Eldarock** [comment]
You can manually create the file, and re-run the application ;)
