### ISSUE TITLE
Can we please get the option to revert changes?

### ISSUE THREAD

**Issue by ebug64** [builtbybel/BloatyNosy#57]
Some Examples:

- I disabled the Bing AI button but now I want to try it. As far as I can tell, there is no way to reenable it. 
- I've accidentally turned on the Subsystem for Linux twice now but I have no idea what it even is nor do I care about it and I had to dig through Google for a way to turn it off (why is it even an enabled recommendation by default?). 
- I may be wrong on this one, but Disabling Game DVR Feature changes the registry. I had disabled it in the past but when I decided I wanted to try it instead of Nvidia, I wasn't able to turn it back on. I once again had to go digging through Google to try and find a way to reenable it through the Registry.
- I have accidentally uninstalled apps that the program flagged as Bloat that I actually use (Sticky Notes, GamingServices, etc.). I had to go find and reinstall them myself, which is a little inconvenient. 

All and all, I LOVE the app and all the hard work you put into it! But I would love it even more if we could reenable/reinstall things too. After all, I'd say the point of this app is empowering freedom of choice. Not much choice in only being able to permanently disable.

**Comment by Belim** [comment]
Hey, this has been possible since the first hour of the app 😲 
![explorer_LYJvGq2hdw](https://github.com/builtbybel/BloatyNosy/assets/57478606/20c2c235-2675-4f31-993e-e5c17f13f7e9)

**Comment by ebug64** [comment]
Oh, my mistake! I thought that option was to revert all the settings back to default, instead of just the selected ones. Thank you for the clarification! ^^
