### ISSUE TITLE
error when pressing fix

### ISSUE THREAD

**Issue by futagyaru** [builtbybel/BloatyNosy#59]
[error 2147942402 (0x80070002) when launching `winget uninstall "windows web experience pack" --silent']

i just started the program, chose what to fix and clicked fix. then i got this

**Comment by Appolon24800** [comment]
SAME help

**Comment by p1xeltw0** [comment]
solved a problem??

**Comment by hkechung** [comment]
update app installer in microsoft store will solve this issue

**Comment by Belim** [comment]
yes
