### ISSUE TITLE
Microsoft Teams crash and restarts

### ISSUE THREAD

**Issue by romain145** [builtbybel/Bloatynosy#60]
After running BloatyNosy in default mode (kept all selected options by default), Microsoft Teams will not run anymore.
The application starts, but closes after a few seconds and restarts showing a banner "There was a glitch, and we had to restart the app. It's good to go now.".
It closes again after a few seconds and restarts again. in loop.
After several restarts it ends up showing this window:

![image](https://github.com/builtbybel/BloatyNosy/assets/4060945/ecae40e9-e545-4e67-92c8-91982d0c1334)

Signing in again does not solve the issue.
Restoring the default state does not solve the issue.
Uninstalling and reinstalling the app does not solve the issue.
Clearing Teams [cache](https://learn.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/clear-teams-cache) does not solve the issue.

**Comment by romain145** [comment]
Restarting Windows fixed the issue.

**Comment by Belim** [comment]
good
