### ISSUE TITLE
How do I Disable the mod AutoLogon? There is no way to disable it in the app.

### ISSUE THREAD

**Issue by MrFolu** [builtbybel/BloatyNosy#68]

**Comment by name-is-in-use** [comment]
This key sets AutoLogon in the Registry HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\AutoAdminLogon  If that is what Bloaty is using, just change the value 1 to a 0 to turn it back off.

**Comment by MrFolu** [comment]
It worked, thank you for the help!!!
