### ISSUE TITLE
Reversion feature?

### ISSUE THREAD

**Issue by PassJim** [builtbybel/BloatyNosy#7]
unchecked biometrics in app, still removed biometrics / depedencies and unable to revert to factory settings,
using the "restore default settings" doesn't seem to work and each time i boot the app following said option it states the same options are disabled despite trying to revert.

**Comment by aet08** [comment]
same issue here, it disabled biometrics, which I did not want to turn off, now I can't reenable it. is there a way to fix it?

**Comment by Belim** [comment]
This function has been removed with the last two builds. However, the undo function has always worked for me until then.
