### ISSUE TITLE
No way to revert options? 

### ISSUE THREAD

**Issue by Her0es** [builtbybel/BloatyNosy#71]
I don't see a way or option to revert changes that the app has done.

**Comment by ElKoto** [comment]
i dont think theres any, but you can redownload the apps by opening powershell and putting this command Get-AppxPackage -allusers | foreach {Add-AppxPackage -register "$($_.InstallLocation)\appxmanifest.xml" -DisableDevelopmentMode}

it will download all the windows preinstall apps

**Comment by Nilser05** [comment]
You just saved me @ElKoto. Somehow some of my Starmenu Icons from Windows Apps completely disappeared (even after restoring with a previously created restore Point). Running this command made them reappear
