### ISSUE TITLE
Uninstall OneDrive option creates annoying issues

### ISSUE THREAD

**Issue by molnizzle** [builtbybel/BloatyNosy#74]
After using BloatyBosy using the default settings, I now get a "Location is not available" popup every single time I open File Explorer. The popup text reads "C:\Users\username\OneDrive\Desktop is not available. If the location is on this PC, make sure the device or drive is connected... blablabla" and it happens 100% of the time, every single time I open File Explorer.

Searching this issue online and there is a bunch of complicated registry hacks and other nonsense required, apparently. Very frustrating because my device is a ROG Ally without easy access to keyboard. A tool like BloatyNosy should just... handle this sort of thing.

**Comment by Dekamir** [comment]
This happens by just uninstalling OneDrive normally. Microsoft broke this.
Yes, BN technically can fix it, but it's not their fault.
