### ISSUE TITLE
BloatyNosyApp 0.85

### ISSUE THREAD

**Issue by bubblesssssss12122112** [builtbybel/Bloatynosy#87]
Hi,
I recently installed this app to de-bloat my windows installation.

Now, I want to revert everything back to how it was before. Is this possible? If it is, may I know how to do it? 

Thanks

**Comment by bubblesssssss12122112** [comment]
Is there any other way?

**Comment by Belim** [comment]
that has been possible since the first hour of the app. i recommend switching to the current release 1.x. here is the restore button placed directly in the main program.
